export * from './lib/components/LegalAdvicePage';
export * from './lib/components/PrivacyPage';
export * from './lib/components/FaqPage';
export * from './lib/components/FaqIndividualsPage';
export * from './lib/components/AboutPage';
export * from './lib/components/AssessmentPolicyPage';
export * from './lib/components/TermsUsePage';
export * from './lib/components/CookiesPage';
export * from './lib/types';
